# Generated by Django 5.1.2 on 2024-10-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
